version: '3.8'

services:
  content-generator-frontend:
    container_name: content-generator-frontend
    build: .
    restart: unless-stopped
    ports:
      - "3002:80" # Permitir peticiones desde el host
    depends_on:
      - content-generator-backend
    networks:
      - app-network

  content-generator-backend:
    container_name: content-generator-backend
    build: ./backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:5002:5002"
    env_file:
      - ./backend/.env
    volumes:
      # Copiaremos el service-account.json en el VPS a esta carpeta
      - /opt/all_in_one_content_generator/backend/service-account.json:/app/service-account.json:ro
    networks:
      - app-network
      - n8n_default

networks:
  app-network:
    driver: bridge
  n8n_default:
    external: true


